services:
  - type: web
    name: cybix-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DEFAULT_PREFIX
        value: "."
      - key: PORT
        value: "8000"
