services:
  - type: web
    name: cybix-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: RENDER
        value: "1"
    ports:
      - port: 8080